repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-yaml
      - id: sort-simple-yaml
      - id: check-added-large-files

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.12.0-2
    hooks:
      - id: shfmt # prebuilt upstream executable

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.5
    hooks:
      - id: shellcheck
        exclude: '^(.*\.zsh|.*\.bats)$'

  - repo: local
    hooks:
      - id: file-set-execution-bit
        name: Set executable permissions on shell scripts
        entry: ./home/dot_config/shell/functions/file-set-execution-bit.sh
        language: script
        files: '\.(sh|bash)$'
        pass_filenames: false
